## 6-е домашнее задание - Библиотека numpy
## Олохтонова Мария 

<b>Срок до 2 июня 2022г. (включительно)</b>

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring_Python_2022</b>» в github в папку "<b>homework-6</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
import numpy as np

a = np.linspace(-1.3,2.5,64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [7]:
n=3
a = np.tile([1,2,3], n)
print(a)

[1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [15]:
def odd(x):
    return 2*x+1
a = np.fromfunction(odd, (10,))
print(a)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [3]:
a = np.zeros((10,10))
a[0] += 1
a[-1] += 1
a[1:-1,0] += 1
a[1:-1,-1] += 1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [25]:
a = np.zeros((8,8))
a[::2,::2] = 1
a[1::2,1::2] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [29]:
def ij(i,j):
    return i+j
n = 5
a = np.fromfunction(ij, (n,n))
print(a)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [38]:
v = np.array([1, 2, 3, 4, 5])
print(v.dot(v), '\n')
print(a.dot(v), '\n')
print(a.dot(a))

55 

[ 40.  55.  70.  85. 100.] 

[[ 30.  40.  50.  60.  70.]
 [ 40.  55.  70.  85. 100.]
 [ 50.  70.  90. 110. 130.]
 [ 60.  85. 110. 135. 160.]
 [ 70. 100. 130. 160. 190.]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [50]:
a = np.cos(np.linspace(0.,1., 20))
b = np.sin(np.linspace(0.,1., 20))
m = np.concatenate((a,b))
print(m)

[1.         0.99861528 0.99446495 0.9875605  0.97792106 0.96557333
 0.95055149 0.93289715 0.91265921 0.88989371 0.8646637  0.83703905
 0.80709627 0.77491828 0.7405942  0.70421909 0.66589368 0.62572411
 0.58382164 0.54030231 0.         0.05260728 0.10506887 0.15723948
 0.20897462 0.26013102 0.310567   0.36014289 0.40872137 0.45616793
 0.50235115 0.54714315 0.59041986 0.63206143 0.67195255 0.70998273
 0.74604665 0.78004444 0.81188195 0.84147098]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [101]:
a = (3 -(-1))*np.random.rand(3,5) + (-1)
print(a)

[[-0.47232845  0.6156555   1.66030151  2.24403583 -0.69433286]
 [ 2.58212744  1.26556133 -0.95915146  0.44251695  0.676492  ]
 [ 2.15778316  0.05053898  2.60289414  0.40419129  0.24881144]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [27]:
m = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print('сумма всех элементов: ', np.sum(m))
print('суммы по столбцам: ', np.sum(m, axis = 0))
print('суммы по строкам: ', np.sum(m, axis = 1))
print('среднее по строкам: ', np.mean(m, axis = 1))
print('дисперсия по строкам: ', np.var(m, axis = 1))
print('стандартное отклонение чисел по строкам: ', np.std(m, axis = 1))

сумма всех элементов:  45
суммы по столбцам:  [12 15 18]
суммы по строкам:  [ 6 15 24]
среднее по строкам:  [2. 5. 8.]
дисперсия по строкам:  [0.66666667 0.66666667 0.66666667]
стандартное отклонение чисел по строкам:  [0.81649658 0.81649658 0.81649658]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [45]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
stdstr = np.std(a, axis = 1).reshape(-1,1)
a = (a - a.mean(axis = 1).reshape(-1,1))/stdstr
print(a)
#a = a / stdstr
#print(a)



[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [105]:
a = np.array([[1, 2, 9], 
              [4, 5, 6], 
              [7, 8, 3]])
print(a[a[:,2].argsort()])

[[7 8 3]
 [4 5 6]
 [1 2 9]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [79]:
#a = np.array([[1, 2, 3], 
#              [4, 5, 6],])
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 10]])
atr = a.transpose()
print(atr)
b = atr.dot(a)
c = a.dot(atr)
print(b)
print(c)
# 3x2 2x3 => 3x3
# 2x3 3x2 => 2x2

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]]
[[ 66  78  97]
 [ 78  93 116]
 [ 97 116 145]]
[[ 14  32  53]
 [ 32  77 128]
 [ 53 128 213]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [80]:
b_sum = sum(np.diag(b))
print(b_sum)
c_sum = sum(np.diag(c))
print(c_sum)

304
304


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [87]:
import numpy.linalg as lg 

print(lg.det(a))
print(lg.det(b))
print(lg.det(c))
print(lg.matrix_rank(a))
print(lg.matrix_rank(b))
print(lg.matrix_rank(c))
print(lg.eigh(b)[0])
print(lg.eigh(c)[0])
# Вывыды: всё совпало для b и c

-2.9999999999999996
8.999999999999526
8.999999999999998
3
3
3
[3.87564271e-02 7.65907389e-01 3.03195336e+02]
[3.87564271e-02 7.65907389e-01 3.03195336e+02]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [106]:
np.random.seed(1032192925)
print(np.random.randint(10))

0


In [122]:
exact = 11 / 2 + np.log(128)
print(exact)

10.352030263919616


In [ ]:
def f(x):
    return (x * x + 3) / (x - 2)

a = 3
b = 4

def rectangle(h):
    n = int((b - a) / h)
    xs = np.linspace(a, b, n + 1)
    ys = f(xs)
    s = np.sum(ys[:-1])
    return s * h

def trapezoid(h):
    n = int((b - a) / h)
    xs = np.linspace(a, b, n + 1)
    ys = f(xs)
    s = np.sum(ys[1:-1])
    return h / 2 * (ys[0] + 2 * s + ys[-1])

def simpson(h):
    n = int((b - a) / h)
    xs = np.linspace(a, b, n + 1)
    ys = f(xs)
    s1 = np.sum(ys[2:-1:2])
    s2 = np.sum(ys[1::2])
    return h / 3 * (ys[0] + 2 * s1 + 4 * s2 + ys[-1])

def find_good_h(title, function):
    h = 0.1
    while True:
        error = np.abs(function(h) - exact)
        if error > 1e-5:
            print(title, 'h = ', h, 'error = ', error)
            h *= 0.1
        else:
            print(title, 'Good h = ', h)
            break
            
find_good_h('rect', rectangle)
find_good_h('trap', trapezoid)
find_good_h('simp', simpson)

rect h =  0.1 error =  0.1293695583083796
rect h =  0.010000000000000002 error =  0.09097611128358629
rect h =  0.0010000000000000002 error =  0.009101592326032915
rect h =  0.00010000000000000003 error =  0.0009101986509492122
rect h =  1.0000000000000004e-05 error =  9.102025888374499e-05
rect h =  1.0000000000000004e-06 error =  9.102029823182534e-06
rect h =  1.0000000000000005e-07 error =  9.102030205099254e-07
rect h =  1.0000000000000005e-08 error =  9.102029530083655e-08
